package relational

import (
	"text-annotation-platform/internal/model/payload"
	"time"
)

// QAPair represents a structured question-answer pair generated by LLM or manually.
type QAPair = payload.QAPair

// Document represents a versioned document stored in the documents table.
// It maps the unstructured 'data' field into a JSON column.
type Document struct {
	ID                     uint       `gorm:"primaryKey;autoIncrement" json:"id"`
	DatasetID              uint       `gorm:"uniqueIndex:idx_doc_version,priority:1;index:idx_dataset_active;index:idx_dataset_updated;index:idx_dataset_stage;index:idx_dataset_user" json:"dataset_id"`
	DocKey                 string     `gorm:"type:varchar(255);uniqueIndex:idx_doc_version,priority:2;index:idx_doc_active" json:"doc_key"`
	Version                int        `gorm:"uniqueIndex:idx_doc_version,priority:3" json:"version"`
	IsActive               bool       `gorm:"index:idx_doc_active;index:idx_dataset_active;index:idx_dataset_updated;index:idx_dataset_stage" json:"is_active"`
	UserID                 uint       `gorm:"index:idx_dataset_user" json:"user_id"`
	Data                   JSON       `gorm:"type:jsonb" json:"data"`
	AnnotationStage        string     `gorm:"type:varchar(50);index:idx_dataset_stage" json:"annotation_stage"`
	RefinementCursor       int        `json:"refinement_cursor"`
	CreatedBy              uint       `json:"created_by"`
	CreatedAt              time.Time  `json:"created_at"`
	UpdatedAt              time.Time  `gorm:"index:idx_dataset_updated" json:"updated_at"`
	ETag                   string     `gorm:"column:etag;type:varchar(64)" json:"etag"`
	LLMRefinementEnabled   bool       `json:"llm_refinement_enabled"`
	LLMRefinementScore     *int       `json:"llm_refinement_score"`
	LLMRefinementReasoning string     `gorm:"type:text" json:"llm_refinement_reasoning"`
	LLMRefinementVersion   string     `gorm:"type:varchar(64)" json:"llm_refinement_version"`
	AnnotatorUserID        string     `gorm:"type:varchar(64)" json:"annotator_user_id"`
	AnnotatorName          string     `gorm:"type:varchar(100)" json:"annotator_name"`
	AnnotatorActionTime    *time.Time `json:"annotator_action_time"`
}
