package service

import (
	"context"
	"encoding/hex"
	"fmt"
	"testing"

	dbmodel "text-annotation-platform/internal/model/relational"
	"text-annotation-platform/internal/repository"
	"text-annotation-platform/internal/testutil"
)

// newTaskTestRepo 跑在真 Postgres 上（独立 schema + 真 goose 迁移）：测试踩到的
// 唯一约束 / 外键就是生产 schema 本身，没有任何 test double。
func newTaskTestRepo(t *testing.T) *repository.DB {
	t.Helper()
	return &repository.DB{DB: testutil.DB(t, repository.RunMigrations)}
}

// seedAssetRow 落真实父行：annotation_tasks 的 asset_id/dataset_id 外键是真的，
// 编造 id 的任务插不进去。identity 是 GENERATED BY DEFAULT，允许显式 id。
func seedAssetRow(t *testing.T, repo *repository.DB, asset *dbmodel.Asset) {
	t.Helper()
	var n int64
	repo.DB.Model(&dbmodel.Dataset{}).Where("id = ?", asset.DatasetID).Count(&n)
	if n == 0 {
		ds := &dbmodel.Dataset{ID: asset.DatasetID, Name: fmt.Sprintf("task-fixture-ds-%d", asset.DatasetID)}
		if err := repo.DB.Create(ds).Error; err != nil {
			t.Fatalf("seed dataset %d: %v", asset.DatasetID, err)
		}
	}
	// 部分唯一索引 idx_assets_dataset_sha 是真的：同数据集里多个 passed 资产
	// 不能共用同一个（空）sha256——给每行合成一个唯一哈希。
	if asset.SHA256 == "" {
		asset.SHA256 = fmt.Sprintf("%064d", asset.ID)
	}
	if err := repo.DB.Create(asset).Error; err != nil {
		t.Fatalf("seed asset %d: %v", asset.ID, err)
	}
}

func TestNewTraceID_FormatAndUniqueness(t *testing.T) {
	a, err := newTraceID()
	if err != nil {
		t.Fatalf("newTraceID: %v", err)
	}
	if len(a) != 32 {
		t.Fatalf("trace id length = %d, want 32 hex chars", len(a))
	}
	if _, err := hex.DecodeString(a); err != nil {
		t.Fatalf("trace id is not hex: %v", err)
	}
	b, _ := newTraceID()
	if a == b {
		t.Fatalf("two trace ids should not collide: %s", a)
	}
}

func TestAnnotationTask_IsTerminal(t *testing.T) {
	terminals := []string{
		dbmodel.TaskStateFinalized,
		dbmodel.TaskStateExported,
		dbmodel.TaskStateQCFailed,
	}
	for _, s := range terminals {
		task := &dbmodel.AnnotationTask{State: s}
		if !task.IsTerminal() {
			t.Errorf("state %s should be terminal", s)
		}
	}
	nonTerminals := []string{
		dbmodel.TaskStateCreated,
		dbmodel.TaskStateRouting,
		dbmodel.TaskStateAIPending,
		dbmodel.TaskStateAIRunning,
		dbmodel.TaskStateHumanPending,
		dbmodel.TaskStateHumanInProgress,
		dbmodel.TaskStateQAPending,
		dbmodel.TaskStateQARejected,
		dbmodel.TaskStateReprocess,
	}
	for _, s := range nonTerminals {
		task := &dbmodel.AnnotationTask{State: s}
		if task.IsTerminal() {
			t.Errorf("state %s should NOT be terminal", s)
		}
	}
}

func TestAnnotationTaskService_CreateForAsset_QCStatusDrivesInitialState(t *testing.T) {
	repo := newTaskTestRepo(t)
	svc := NewAnnotationTaskService(repo)
	ctx := context.Background()

	cases := []struct {
		name      string
		qc        string
		wantState string
	}{
		{"qc passed → ROUTING", dbmodel.QCStatusPassed, dbmodel.TaskStateRouting},
		{"qc failed → QC_FAILED", dbmodel.QCStatusFailed, dbmodel.TaskStateQCFailed},
		{"qc pending → CREATED", dbmodel.QCStatusPending, dbmodel.TaskStateCreated},
	}
	for i, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			asset := &dbmodel.Asset{
				ID:        uint(i + 1),
				DatasetID: 42,
				QCStatus:  tc.qc,
			}
			seedAssetRow(t, repo, asset)
			task, err := svc.CreateForAsset(ctx, asset, CreateTaskOptions{})
			if err != nil {
				t.Fatalf("CreateForAsset: %v", err)
			}
			if task.State != tc.wantState {
				t.Fatalf("state = %s, want %s", task.State, tc.wantState)
			}
			if task.AssetID != asset.ID {
				t.Fatalf("asset id mismatch: %d vs %d", task.AssetID, asset.ID)
			}
			if task.DatasetID != asset.DatasetID {
				t.Fatalf("dataset id mismatch: %d vs %d", task.DatasetID, asset.DatasetID)
			}
			if len(task.TraceID) != 32 {
				t.Fatalf("trace id should be 32 hex chars, got %q", task.TraceID)
			}
			if task.Version != 1 {
				t.Fatalf("initial version = %d, want 1", task.Version)
			}
			if task.StrategyOrigin != dbmodel.StrategyOriginAuto {
				t.Fatalf("strategy origin = %s, want AUTO", task.StrategyOrigin)
			}
		})
	}
}

// T0.1: audio/video assets skip the image-only L1 router. On QC pass they go
// straight to HUMAN_PENDING with a HUMAN_ONLY strategy (no AI in M0).
func TestAnnotationTaskService_CreateForAsset_AVSkipsRouting(t *testing.T) {
	repo := newTaskTestRepo(t)
	svc := NewAnnotationTaskService(repo)
	ctx := context.Background()

	cases := []struct {
		name      string
		modality  string
		wantState string
		wantRoute string
	}{
		// Audio/Video skip the image L1 router → HUMAN_PENDING; AI prelabel is
		// on-demand via /tasks/:id/invoke (not auto on import).
		{"audio → HUMAN_PENDING/HUMAN_ONLY", dbmodel.ModalityAudio, dbmodel.TaskStateHumanPending, dbmodel.RouteHumanOnly},
		{"video → HUMAN_PENDING/HUMAN_ONLY", dbmodel.ModalityVideo, dbmodel.TaskStateHumanPending, dbmodel.RouteHumanOnly},
		{"image → ROUTING", dbmodel.ModalityImage, dbmodel.TaskStateRouting, ""},
	}
	for i, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			asset := &dbmodel.Asset{
				ID:        uint(100 + i),
				DatasetID: 7,
				Modality:  tc.modality,
				QCStatus:  dbmodel.QCStatusPassed,
			}
			seedAssetRow(t, repo, asset)
			task, err := svc.CreateForAsset(ctx, asset, CreateTaskOptions{})
			if err != nil {
				t.Fatalf("CreateForAsset: %v", err)
			}
			if task.State != tc.wantState {
				t.Fatalf("state = %s, want %s", task.State, tc.wantState)
			}
			if tc.modality != dbmodel.ModalityImage && task.RouteStrategy != tc.wantRoute {
				t.Fatalf("route = %q, want %q", task.RouteStrategy, tc.wantRoute)
			}
		})
	}
}

func TestAnnotationTaskService_CreateForAsset_RejectsInvalidAsset(t *testing.T) {
	svc := NewAnnotationTaskService(newTaskTestRepo(t))
	if _, err := svc.CreateForAsset(context.Background(), nil, CreateTaskOptions{}); err == nil {
		t.Fatalf("nil asset should error")
	}
	if _, err := svc.CreateForAsset(context.Background(), &dbmodel.Asset{}, CreateTaskOptions{}); err == nil {
		t.Fatalf("zero asset id should error")
	}
}

func TestAnnotationTaskService_Reprocess_OnlyTerminalAllowed(t *testing.T) {
	repo := newTaskTestRepo(t)
	svc := NewAnnotationTaskService(repo)
	ctx := context.Background()

	// Seed a task in HUMAN_PENDING (non-terminal). Reprocess should refuse.
	asset := &dbmodel.Asset{ID: 1, DatasetID: 1, QCStatus: dbmodel.QCStatusPassed}
	seedAssetRow(t, repo, asset)
	task, err := svc.CreateForAsset(ctx, asset, CreateTaskOptions{})
	if err != nil {
		t.Fatalf("seed: %v", err)
	}
	// Force into a non-terminal state.
	if err := repo.UpdateAnnotationTask(context.Background(), task.ID, map[string]interface{}{"state": dbmodel.TaskStateHumanPending}); err != nil {
		t.Fatalf("force state: %v", err)
	}
	if err := svc.Reprocess(ctx, task.ID); err == nil {
		t.Fatalf("expected error reprocessing non-terminal task")
	}

	// Move to FINALIZED → reprocess should succeed and bump version.
	if err := repo.UpdateAnnotationTask(context.Background(), task.ID, map[string]interface{}{"state": dbmodel.TaskStateFinalized}); err != nil {
		t.Fatalf("force terminal: %v", err)
	}
	if err := svc.Reprocess(ctx, task.ID); err != nil {
		t.Fatalf("reprocess terminal: %v", err)
	}
	got, err := repo.FindAnnotationTaskByID(context.Background(), task.ID)
	if err != nil {
		t.Fatalf("refetch: %v", err)
	}
	if got.State != dbmodel.TaskStateRouting {
		t.Fatalf("state after reprocess = %s, want ROUTING", got.State)
	}
	if got.Version != task.Version+1 {
		t.Fatalf("version after reprocess = %d, want %d", got.Version, task.Version+1)
	}
	if got.RetryCount != 0 {
		t.Fatalf("retry count after reprocess = %d, want 0", got.RetryCount)
	}
	if got.TraceID == task.TraceID {
		t.Fatalf("trace id should rotate on reprocess")
	}
}
