package service

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"time"

	paymodel "text-annotation-platform/internal/model/payload"
	dbmodel "text-annotation-platform/internal/model/relational"
	"text-annotation-platform/internal/plugin"
	"text-annotation-platform/internal/repository"
)

// LLMDegradedError is returned when the LLM service is unavailable after all retries.
type LLMDegradedError struct {
	Cause   error
	Retries int
}

func (e *LLMDegradedError) Error() string {
	return fmt.Sprintf("LLM 服务暂不可用（已重试 %d 次）: %v", e.Retries, e.Cause)
}

// QACandidate represents a single question-answer pair generated by the LLM.
type QACandidate struct {
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

// LLMRequest holds parameters for QA candidate generation.
type LLMRequest struct {
	DocKey   string `json:"doc_key"`
	TextSpan string `json:"text_span"`
	MaxItems int    `json:"max_items"`
	QAStyle  string `json:"qa_style"`
}

// LLMServiceConfig captures runtime tuning knobs that used to be hard-coded.
type LLMServiceConfig struct {
	// MinProviderTimeout is the floor applied to TimeoutSeconds when building
	// adapters from DB-provisioned providers. Defaults to 180s.
	MinProviderTimeout time.Duration
	// RetryMaxBackoff caps the exponential backoff between provider retries.
	// Defaults to 30s.
	RetryMaxBackoff time.Duration
}

// LLMService manages multiple LLM providers via the adapter pattern and exposes
// QA generation routed through CapabilityService for unified trace logging.
type LLMService struct {
	mu           sync.RWMutex
	adapters     map[uint]LLMProviderAdapter
	taskRegistry *plugin.PluginRegistry[plugin.TaskPlugin]
	dbRepo    *repository.DB
	capSvc       *CapabilityService
	cfg          LLMServiceConfig
}

// NewLLMService creates a new LLMService. capSvc is used by GenerateQACandidates
// to route text.chat calls through the unified trace-logging path.
func NewLLMService(
	dbRepo *repository.DB,
	taskRegistry *plugin.PluginRegistry[plugin.TaskPlugin],
	capSvc *CapabilityService,
	cfg LLMServiceConfig,
) *LLMService {
	if cfg.MinProviderTimeout <= 0 {
		cfg.MinProviderTimeout = 180 * time.Second
	}
	if cfg.RetryMaxBackoff <= 0 {
		cfg.RetryMaxBackoff = 30 * time.Second
	}
	return &LLMService{
		adapters:     make(map[uint]LLMProviderAdapter),
		taskRegistry: taskRegistry,
		dbRepo:    dbRepo,
		capSvc:       capSvc,
		cfg:          cfg,
	}
}

// ReloadAdapters queries all enabled text.chat LLMProviders from the relational DB and
// rebuilds the adapter map.
func (s *LLMService) ReloadAdapters(ctx context.Context) error {
	var providers []dbmodel.LLMProvider
	if err := s.dbRepo.DB.
		Scopes(repository.EnabledTextChatProvidersScope).
		Find(&providers).Error; err != nil {
		return fmt.Errorf("query LLM providers failed: %w", err)
	}

	newAdapters := make(map[uint]LLMProviderAdapter, len(providers))
	for _, p := range providers {
		timeout := time.Duration(p.TimeoutSeconds) * time.Second
		if timeout < s.cfg.MinProviderTimeout {
			timeout = s.cfg.MinProviderTimeout
		}
		switch p.Type {
		case "ollama":
			newAdapters[p.ID] = NewOllamaAdapter(p.Endpoint, p.Model, timeout)
		case "openai_compatible", "deepseek", "qwen", "openai", "litellm":
			newAdapters[p.ID] = NewOpenAICompatibleAdapter(p.Endpoint, p.APIKey, p.Model, timeout)
		default:
			continue
		}
	}

	s.mu.Lock()
	s.adapters = newAdapters
	s.mu.Unlock()
	return nil
}

func (s *LLMService) getAdapter(providerID uint) (LLMProviderAdapter, error) {
	s.mu.RLock()
	adapter, ok := s.adapters[providerID]
	s.mu.RUnlock()
	if !ok {
		return nil, fmt.Errorf("LLM provider not found or disabled (ID: %d)", providerID)
	}
	return adapter, nil
}

// CallWithProvider calls the LLM using the specified provider.
func (s *LLMService) CallWithProvider(ctx context.Context, providerID uint, systemPrompt, userPrompt string, opts ...LLMCallOptions) (string, error) {
	adapter, err := s.getAdapter(providerID)
	if err != nil {
		return "", err
	}
	return adapter.Call(ctx, systemPrompt, userPrompt, opts...)
}

// CallWithRetry calls the LLM with exponential backoff retry using the provider's config.
func (s *LLMService) CallWithRetry(ctx context.Context, providerID uint, systemPrompt, userPrompt string, opts ...LLMCallOptions) (string, error) {
	adapter, err := s.getAdapter(providerID)
	if err != nil {
		return "", err
	}

	provider, err := s.GetProvider(providerID)
	if err != nil {
		return "", err
	}

	maxRetries := provider.MaxRetries
	if maxRetries <= 0 {
		maxRetries = 3
	}

	var lastErr error
	backoff := time.Second

	for i := 0; i <= maxRetries; i++ {
		result, callErr := adapter.Call(ctx, systemPrompt, userPrompt, opts...)
		if callErr == nil {
			return result, nil
		}
		lastErr = callErr
		if i < maxRetries {
			select {
			case <-ctx.Done():
				return "", ctx.Err()
			case <-time.After(backoff):
			}
			backoff *= 2
			if backoff > s.cfg.RetryMaxBackoff {
				backoff = s.cfg.RetryMaxBackoff
			}
		}
	}
	return "", &LLMDegradedError{Cause: lastErr, Retries: maxRetries}
}

// TestConnection tests the connectivity of the specified provider.
func (s *LLMService) TestConnection(ctx context.Context, providerID uint) (latencyMs int64, preview string, err error) {
	adapter, adapterErr := s.getAdapter(providerID)
	if adapterErr != nil {
		return 0, "", adapterErr
	}
	return adapter.TestConnection(ctx)
}

// GetProvider queries a single LLM provider by ID from the relational DB.
func (s *LLMService) GetProvider(providerID uint) (*dbmodel.LLMProvider, error) {
	var provider dbmodel.LLMProvider
	if err := s.dbRepo.DB.First(&provider, providerID).Error; err != nil {
		return nil, fmt.Errorf("LLM provider not found (ID: %d): %w", providerID, err)
	}
	return &provider, nil
}

// ProviderIDByModel returns the ID of the first enabled text.chat provider
// whose Model or Name contains model (case-insensitive). Falls back to the
// highest-priority enabled provider when model is empty or unmatched.
func (s *LLMService) ProviderIDByModel(model string) uint {
	var providers []dbmodel.LLMProvider
	s.dbRepo.DB.
		Scopes(repository.EnabledTextChatProvidersScope).
		Order("priority DESC, id ASC").
		Find(&providers)
	if len(providers) == 0 {
		return 0
	}
	if model != "" {
		lower := strings.ToLower(model)
		for _, p := range providers {
			if strings.Contains(strings.ToLower(p.Model), lower) || strings.EqualFold(p.Name, model) {
				return p.ID
			}
		}
	}
	return providers[0].ID
}

// GenerateQACandidates uses the qa_generation task plugin to build a prompt and
// routes the LLM call through CapabilityService (text.chat) for unified trace
// logging and multi-provider support.
func (s *LLMService) GenerateQACandidates(ctx context.Context, req LLMRequest) ([]QACandidate, error) {
	qaPlugin, err := s.taskRegistry.Get("qa_generation")
	if err != nil {
		return nil, fmt.Errorf("QA generation plugin not found: %w", err)
	}

	params := map[string]interface{}{}
	if req.MaxItems > 0 {
		params["max_items"] = req.MaxItems
	}
	if req.QAStyle != "" {
		params["qa_style"] = req.QAStyle
	}

	prompt, err := qaPlugin.BuildPrompt(req.TextSpan, params)
	if err != nil {
		return nil, fmt.Errorf("build QA prompt failed: %w", err)
	}

	capResp, err := s.capSvc.Invoke(ctx, CapabilityRequest{
		CapabilityType: CapabilityTextChat,
		Prompt:         prompt,
	})
	if err != nil {
		return nil, err
	}

	result, err := qaPlugin.ParseResult(capResp.Text)
	if err != nil {
		return nil, fmt.Errorf("parse QA result failed: %w", err)
	}

	if err := qaPlugin.ValidateResult(result); err != nil {
		return nil, fmt.Errorf("validate QA result failed: %w", err)
	}

	qaPairs := paymodel.ParseQAPairs(result)
	if len(qaPairs) == 0 {
		return nil, fmt.Errorf("LLM 未返回有效 QA 对")
	}

	candidates := make([]QACandidate, len(qaPairs))
	for i, p := range qaPairs {
		candidates[i] = QACandidate{Question: p.Question, Answer: p.Answer}
	}
	return candidates, nil
}

// ListTaskTypes returns info about all registered task types.
func (s *LLMService) ListTaskTypes() []plugin.TaskTypeInfo {
	plugins := s.taskRegistry.List()
	types := make([]plugin.TaskTypeInfo, 0, len(plugins))
	for _, p := range plugins {
		types = append(types, plugin.TaskTypeInfo{
			TypeID: p.TypeID(),
			Name:   p.Name(),
		})
	}
	return types
}
