package payload

import (
	"time"
)

// Document represents a versioned document stored in the documents table.
type Document struct {
	ID                     string                 `json:"id"`
	DatasetID              uint                   `json:"dataset_id"`
	DocKey                 string                 `json:"doc_key"`
	Version                int                    `json:"version"`
	IsActive               bool                   `json:"is_active"`
	UserID                 uint                   `json:"user_id"`
	Data                   map[string]interface{} `json:"data"`
	AnnotationStage        string                 `json:"annotation_stage"`
	RefinementCursor       int                    `json:"refinement_cursor"`
	CreatedBy              uint                   `json:"created_by"`
	CreatedAt              JSONTime               `json:"created_at"`
	UpdatedAt              JSONTime               `json:"updated_at"`
	ETag                   string                 `json:"etag"`
	LLMRefinementEnabled   bool                   `json:"llm_refinement_enabled"`
	LLMRefinementScore     *int                   `json:"llm_refinement_score"`
	LLMRefinementReasoning string                 `json:"llm_refinement_reasoning"`
	LLMRefinementVersion   string                 `json:"llm_refinement_version"`
	AnnotatorUserID        string                 `json:"annotator_user_id"`
	AnnotatorName          string                 `json:"annotator_name"`
	AnnotatorActionTime    *JSONTime              `json:"annotator_action_time"`
}

// QAPair represents a structured question-answer pair generated by LLM or manually.
type QAPair struct {
	Question              string                 `json:"question"`
	Answer                string                 `json:"answer"`
	QuestionKey           string                 `json:"question_key,omitempty"`
	Category              string                 `json:"category,omitempty"`
	Evidence              string                 `json:"evidence,omitempty"`
	Confidence            *float64               `json:"confidence,omitempty"`
	Reason                string                 `json:"reason,omitempty"`
	Source                string                 `json:"source"`
	Confirmed             bool                   `json:"confirmed"`
	SpanText              string                 `json:"span_text,omitempty"`
	SpanStart             *int                   `json:"span_start,omitempty"`
	SpanEnd               *int                   `json:"span_end,omitempty"`
	TextField             string                 `json:"text_field,omitempty"`
	ProviderID            uint                   `json:"provider_id,omitempty"`
	ProviderName          string                 `json:"provider_name,omitempty"`
	Model                 string                 `json:"model,omitempty"`
	PromptTemplateID      uint                   `json:"prompt_template_id,omitempty"`
	PromptTemplateName    string                 `json:"prompt_template_name,omitempty"`
	PromptVersion         int                    `json:"prompt_version,omitempty"`
	CandidateRunID        string                 `json:"candidate_run_id,omitempty"`
	JudgeRunID            string                 `json:"judge_run_id,omitempty"`
	SourceCandidateRunIDs []string               `json:"source_candidate_run_ids,omitempty"`
	EditedAfterAdopt      bool                   `json:"edited_after_adopt,omitempty"`
	Meta                  map[string]interface{} `json:"meta,omitempty"`
}

// ParsedDocument represents a document parsed from an import file.
type ParsedDocument struct {
	DocKey string                 `json:"doc_key"`
	Data   map[string]interface{} `json:"data"`
}

// ExportDocument represents a document prepared for export.
type ExportDocument struct {
	DocKey    string                 `json:"doc_key"`
	Version   int                    `json:"version"`
	Data      map[string]interface{} `json:"data"`
	CreatedBy uint                   `json:"created_by"`
	UpdatedAt time.Time              `json:"updated_at"`
	// Envelope, when non-nil, is the 《通用元数据字段》 record the export plugins
	// serialize instead of the legacy {doc_key,version,data,created_by} shape.
	Envelope map[string]interface{} `json:"-"`
}
