-- +goose Up
-- =============================================================================
-- Postgres 目标态 schema（执行方案-06 · P1）。本文件是关系库 schema 的**唯一真源**：
-- AutoMigrate 已删除（M3），dev 与 prod 跑的都是这一份（D1）。
--
-- 这是干净起点：没有存量库要升级，历史上的多文件迁移链已收敛为这一个
-- 建库迁移（含 datasets 的九个看板计数列——内容零丢失）。
--
-- ⚠️ 运维禁令（06 · P-H1 立的，07 载荷入库后仍然有效）：
--   ❌ TRUNCATE ... RESTART IDENTITY      ❌ ALTER SEQUENCE ... RESTART
--   07 之后载荷表与本库同库且 FK 级联，「清一半」类事故已编不出来；但
--   trace_logs 刻意无 FK（可观测性比对象活得久），id 重用会把旧 trace 缝到
--   新任务上。清环境的正路是整库 DROP DATABASE 重建 + Redis db1 flushdb +
--   清 blob 目录，别做表级局部清理。
--
-- 外键策略（M7）：级联只加在**数据脊柱**上（datasets → assets → tasks/derivatives/
-- uploads/documents…），删数据集即级联清光其下的关系行——修掉「删数据集不级联删
-- 资产」的泄漏。**不加指向 users(id) 的外键**：owner_id/user_id/uploader_id 的
-- 「0 = 系统/未指定」是既有写入约定，加 FK 会立刻炸掉现有代码路径；用户删除本就
-- 不该抹掉审计与产出的归属。
--
-- asset_derivatives.kind **刻意不做 CHECK/枚举约束**（06 · §6.2，2026-07-14 评审）：
-- kind 清单随 Phase C/D 扩（dzi_tiles/volume_slices/pcd_tiles/…），做成 DB 枚举
-- = C/D 开工第一天就二次迁移。校验留在应用层（Go 常量）。
-- =============================================================================

-- documents 全文检索用 trigram GIN（M5：CAST(data AS TEXT) LIKE 的 Postgres 对等物）。
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL DEFAULT 'annotator',
    employee_id   VARCHAR(64)  UNIQUE,
    email         VARCHAR(128) UNIQUE,
    sso_id        VARCHAR(128) UNIQUE,
    status        VARCHAR(20)  NOT NULL DEFAULT 'active',
    display_name  TEXT         NOT NULL DEFAULT '',
    last_login_at timestamptz,
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_last_login_at ON users(last_login_at);

CREATE TABLE dataset_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description TEXT         NOT NULL DEFAULT ''
);

CREATE TABLE tags (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(50) NOT NULL,
    color VARCHAR(20) NOT NULL DEFAULT '',
    type  VARCHAR(30) NOT NULL DEFAULT 'dataset',
    UNIQUE (name, type)
);

CREATE TABLE dataset_functions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE,
    description     TEXT         NOT NULL DEFAULT '',
    workflow_config TEXT         NOT NULL DEFAULT '{}',
    layout_config   TEXT,
    sort_order      INTEGER      NOT NULL DEFAULT 0,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE datasets (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(200) NOT NULL,
    category_id         BIGINT       REFERENCES dataset_categories(id) ON DELETE SET NULL,
    owner_id            BIGINT       NOT NULL DEFAULT 0,
    user_id             BIGINT       NOT NULL DEFAULT 1,
    annotation_type     VARCHAR(50)  NOT NULL DEFAULT 'qa',
    modality            VARCHAR(16)  NOT NULL DEFAULT 'text',
    version             INTEGER      NOT NULL DEFAULT 1,
    case_type           VARCHAR(50)  NOT NULL DEFAULT 'criminal',
    dataset_function_id BIGINT       REFERENCES dataset_functions(id) ON DELETE SET NULL,
    label_config        TEXT         NOT NULL DEFAULT '[]',
    label_ontology      TEXT         NOT NULL DEFAULT '{}',
    -- 导出信封元数据（《通用元数据字段》规范，原 000006）
    auth_type           VARCHAR(32)  NOT NULL DEFAULT '',
    source_type         VARCHAR(64)  NOT NULL DEFAULT '',
    source_detail       TEXT         NOT NULL DEFAULT '{}',
    data_version        VARCHAR(32)  NOT NULL DEFAULT '',
    -- M11：数据集级 AI 配置收敛为一列，按 capability 分键，如
    --   {"video.detect_track": {"trigger":"manual","max_frames":600, ...}}
    -- 原 video_ai_config（000007）并入 "video.detect_track" 键；plan_v3 D-01 的
    -- default_config（文本线能力键）将来也写进这一列。判据：加模态零改列。
    -- '{}'::jsonb = 全部用全局默认。
    ai_config           JSONB        NOT NULL DEFAULT '{}'::jsonb,
    -- 看板计数列（原 000008_dataset_counters.go，已并入建表）
    doc_count             INTEGER NOT NULL DEFAULT 0,
    not_annotated_count   INTEGER NOT NULL DEFAULT 0,
    auto_annotating_count INTEGER NOT NULL DEFAULT 0,
    auto_annotated_count  INTEGER NOT NULL DEFAULT 0,
    auto_failed_count     INTEGER NOT NULL DEFAULT 0,
    refining_count        INTEGER NOT NULL DEFAULT 0,
    refined_count         INTEGER NOT NULL DEFAULT 0,
    reviewed_count        INTEGER NOT NULL DEFAULT 0,
    qa_total              INTEGER NOT NULL DEFAULT 0,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_datasets_category_id      ON datasets(category_id);
CREATE INDEX idx_datasets_owner_id         ON datasets(owner_id);
CREATE INDEX idx_datasets_user_id          ON datasets(user_id);
CREATE INDEX idx_datasets_modality         ON datasets(modality);
CREATE INDEX idx_datasets_dataset_function ON datasets(dataset_function_id);

CREATE TABLE dataset_tags (
    dataset_id BIGINT NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    tag_id     BIGINT NOT NULL REFERENCES tags(id)     ON DELETE CASCADE,
    PRIMARY KEY (dataset_id, tag_id)
);

CREATE TABLE dataset_industry_tags (
    dataset_id BIGINT NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    tag_id     BIGINT NOT NULL REFERENCES tags(id)     ON DELETE CASCADE,
    PRIMARY KEY (dataset_id, tag_id)
);

-- 审计日志不加 FK：日志必须活得比它指向的对象久。
CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action      VARCHAR(50)  NOT NULL DEFAULT '',
    target_type VARCHAR(50)  NOT NULL DEFAULT '',
    target_id   VARCHAR(100) NOT NULL DEFAULT '',
    user_id     BIGINT       NOT NULL DEFAULT 1,
    result      VARCHAR(20)  NOT NULL DEFAULT '',
    detail      TEXT         NOT NULL DEFAULT '',
    created_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_action     ON audit_logs(action);
CREATE INDEX idx_audit_logs_user_id    ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);

CREATE TABLE system_prompts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_type  VARCHAR(50)  NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL DEFAULT '',
    content    TEXT         NOT NULL DEFAULT '',
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);

-- llm_providers 含 Phase 2 能力中心列（原 000002 的 ALTER 已并入建表；
-- cmd/main.go 启动期吞错误的 ALTER TABLE 补丁随之删除——M4）。
CREATE TABLE llm_providers (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(100) NOT NULL DEFAULT '',
    type                 VARCHAR(30)  NOT NULL DEFAULT '',
    endpoint             VARCHAR(500) NOT NULL DEFAULT '',
    api_key              VARCHAR(500) NOT NULL DEFAULT '',
    model                VARCHAR(100) NOT NULL DEFAULT '',
    enabled              BOOLEAN      NOT NULL DEFAULT TRUE,
    timeout_seconds      INTEGER      NOT NULL DEFAULT 60,
    max_retries          INTEGER      NOT NULL DEFAULT 3,
    last_test_success    BOOLEAN,
    last_test_at         timestamptz,
    last_test_latency_ms INTEGER,
    capability_type      VARCHAR(64)  NOT NULL DEFAULT 'text.chat',
    provider_kind        VARCHAR(32)  NOT NULL DEFAULT '',
    extra_config         TEXT,
    priority             INTEGER      NOT NULL DEFAULT 0,
    created_at           timestamptz  NOT NULL DEFAULT now(),
    updated_at           timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE extraction_results (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id    BIGINT       NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    name          VARCHAR(200) NOT NULL DEFAULT '',
    filter_config TEXT         NOT NULL DEFAULT '{}',
    doc_keys      TEXT         NOT NULL DEFAULT '[]',
    matched_count INTEGER      NOT NULL DEFAULT 0,
    total_count   INTEGER      NOT NULL DEFAULT 0,
    created_at    timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_extraction_results_dataset ON extraction_results(dataset_id);

-- doc_id 是 documents 的字符串键（doc_key），不是本库整数 id → 无 FK。
CREATE TABLE annotation_logs (
    log_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id      VARCHAR(64) NOT NULL DEFAULT '',
    user_id     BIGINT      NOT NULL DEFAULT 0,
    action      VARCHAR(32) NOT NULL DEFAULT '',
    from_status VARCHAR(32) NOT NULL DEFAULT '',
    to_status   VARCHAR(32) NOT NULL DEFAULT '',
    score       INTEGER,
    details     TEXT,
    reasoning   TEXT,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_annotation_logs_doc_id     ON annotation_logs(doc_id);
CREATE INDEX idx_annotation_logs_user_id    ON annotation_logs(user_id);
CREATE INDEX idx_annotation_logs_created_at ON annotation_logs(created_at);

-- =============================================================================
-- assets：sha256 语义（M6，2026-07-14 评审拍板，Phase C/D 前置）
--   · 单文件资产（现状全部）：sha256 = 文件内容哈希，storage_uri 指向该对象。
--   · 多文件资产（Phase C 的 DICOM series / Phase D 的 scene）：storage_uri 指向
--     一份 **manifest 清单对象**，sha256 = manifest 内容哈希（清单里逐文件记 sha）。
--   两种情形下 UNIQUE 与 NOT NULL 语义一致成立；单文件是多文件的退化情形。
--
-- 去重唯一键是**部分唯一索引**（只覆盖 qc_status='passed'）：
--   · 去重逻辑本来就只对 QC 通过的资产生效（QC 失败行是给操作员看的拒收记录，
--     同一个坏文件反复上传、或坏文件与已入库的好文件同内容，都不该撞唯一键）。
--   · 上传路径用 ON CONFLICT (dataset_id, sha256) WHERE qc_status='passed'
--     DO NOTHING → 唯一性成为**数据库的属性**，并发上传同一文件不再插两行
--     （旧的「先查后写」竞态从此关死）。
-- =============================================================================
CREATE TABLE assets (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id      BIGINT       NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    parent_asset_id BIGINT       REFERENCES assets(id) ON DELETE CASCADE,
    modality        VARCHAR(16)  NOT NULL DEFAULT 'image',
    storage_uri     VARCHAR(512) NOT NULL DEFAULT '',
    original_name   VARCHAR(512) NOT NULL DEFAULT '',
    mime            VARCHAR(64)  NOT NULL DEFAULT '',
    sha256          VARCHAR(64)  NOT NULL DEFAULT '',
    size_bytes      BIGINT       NOT NULL DEFAULT 0,
    width           INTEGER      NOT NULL DEFAULT 0,
    height          INTEGER      NOT NULL DEFAULT 0,
    duration_ms     BIGINT,
    fps             DOUBLE PRECISION,
    sample_rate     INTEGER,
    qc_status       VARCHAR(16)  NOT NULL DEFAULT 'pending',
    qc_report       JSONB,
    features        JSONB,
    preprocess_status          VARCHAR(16),
    preprocess_error           TEXT,
    preprocess_attempts        INTEGER NOT NULL DEFAULT 0,
    preprocess_lease_until     timestamptz,
    preprocess_next_attempt_at timestamptz,
    uploader_id     BIGINT       NOT NULL DEFAULT 0,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    updated_at      timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_assets_dataset_id      ON assets(dataset_id);
CREATE INDEX idx_assets_parent_asset_id ON assets(parent_asset_id);
CREATE INDEX idx_assets_modality        ON assets(modality);
CREATE INDEX idx_assets_sha256          ON assets(sha256);
CREATE INDEX idx_assets_qc_status       ON assets(qc_status);
CREATE INDEX idx_assets_uploader_id     ON assets(uploader_id);
CREATE INDEX idx_assets_preprocess_status ON assets(preprocess_status);
CREATE INDEX idx_assets_preprocess_next   ON assets(preprocess_next_attempt_at);

-- M6：去重唯一键（部分唯一索引，理由见上方大注释）。
CREATE UNIQUE INDEX idx_assets_dataset_sha
    ON assets(dataset_id, sha256) WHERE qc_status = 'passed';

CREATE TABLE annotation_tasks (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id                BIGINT      NOT NULL REFERENCES assets(id)   ON DELETE CASCADE,
    dataset_id              BIGINT      NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    job_id                  BIGINT,
    parent_asset_id         BIGINT,
    route_strategy          VARCHAR(32) NOT NULL DEFAULT '',
    strategy_origin         VARCHAR(16) NOT NULL DEFAULT 'AUTO',
    strategy_review_note    TEXT        NOT NULL DEFAULT '',
    state                   VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    assignee_id             BIGINT,
    reviewer_id             BIGINT,
    trace_id                VARCHAR(64) NOT NULL DEFAULT '',
    retry_count             INTEGER     NOT NULL DEFAULT 0,
    version                 INTEGER     NOT NULL DEFAULT 1,
    deadline_at             timestamptz,
    cost                    NUMERIC(12,6) NOT NULL DEFAULT 0,
    latency_ms              BIGINT      NOT NULL DEFAULT 0,
    ai_run_ids              JSONB,
    human_annotation_id     VARCHAR(64) NOT NULL DEFAULT '',
    final_annotation_id     VARCHAR(64) NOT NULL DEFAULT '',
    error                   JSONB,
    human_only_fallback     BOOLEAN     NOT NULL DEFAULT FALSE,
    routing_review_deadline timestamptz,
    next_attempt_at         timestamptz,
    lease_until             timestamptz,
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_annotation_tasks_asset_id   ON annotation_tasks(asset_id);
CREATE INDEX idx_annotation_tasks_dataset_id ON annotation_tasks(dataset_id);
CREATE INDEX idx_annotation_tasks_job_id     ON annotation_tasks(job_id);
CREATE INDEX idx_annotation_tasks_state      ON annotation_tasks(state);
CREATE INDEX idx_annotation_tasks_trace_id   ON annotation_tasks(trace_id);
CREATE INDEX idx_annotation_tasks_next_at    ON annotation_tasks(next_attempt_at);
CREATE INDEX idx_annotation_tasks_lease      ON annotation_tasks(lease_until);

-- kind 无 CHECK 约束是刻意的（见文件头）。storage_uri 对目录型派生物
-- （Phase C 的 DZI 瓦片、Phase D 的 cam_frames）承载**前缀**语义，
-- 由应用层按 kind 解释（06 · §6.2）。
CREATE TABLE asset_derivatives (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id    BIGINT       NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    kind        VARCHAR(24)  NOT NULL,
    version     INTEGER      NOT NULL DEFAULT 1,
    params_hash VARCHAR(32)  NOT NULL DEFAULT '',
    storage_uri VARCHAR(512) NOT NULL DEFAULT '',
    status      VARCHAR(16)  NOT NULL DEFAULT 'ready',
    size_bytes  BIGINT       NOT NULL DEFAULT 0,
    sha256      VARCHAR(64)  NOT NULL DEFAULT '',
    error       TEXT,
    created_at  timestamptz  NOT NULL DEFAULT now(),
    updated_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_deriv_asset_kind ON asset_derivatives (asset_id, kind);

CREATE TABLE upload_sessions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       VARCHAR(40)  NOT NULL,
    upload_id        VARCHAR(256) NOT NULL DEFAULT '',
    user_id          BIGINT       NOT NULL DEFAULT 0,
    dataset_id       BIGINT       NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    modality         VARCHAR(16)  NOT NULL DEFAULT '',
    filename         VARCHAR(512) NOT NULL DEFAULT '',
    content_type     VARCHAR(128) NOT NULL DEFAULT '',
    size_bytes       BIGINT       NOT NULL DEFAULT 0,
    part_size        BIGINT       NOT NULL DEFAULT 0,
    temp_object_key  VARCHAR(512) NOT NULL DEFAULT '',
    final_object_key VARCHAR(512) NOT NULL DEFAULT '',
    client_sha256    VARCHAR(64)  NOT NULL DEFAULT '',
    server_sha256    VARCHAR(64)  NOT NULL DEFAULT '',
    status           VARCHAR(16)  NOT NULL DEFAULT 'pending',
    error            TEXT,
    asset_id         BIGINT       REFERENCES assets(id) ON DELETE SET NULL,
    expires_at       timestamptz,
    completed_at     timestamptz,
    created_at       timestamptz  NOT NULL DEFAULT now(),
    updated_at       timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX idx_upload_session_id ON upload_sessions (session_id);
CREATE INDEX idx_upload_status  ON upload_sessions (status);
CREATE INDEX idx_upload_expires ON upload_sessions (expires_at);

CREATE TABLE batch_jobs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      VARCHAR(32)  NOT NULL,
    dataset_id  BIGINT       NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    capability  VARCHAR(64)  NOT NULL DEFAULT '',
    model       VARCHAR(128) NOT NULL DEFAULT '',
    total       INTEGER      NOT NULL DEFAULT 0,
    done        INTEGER      NOT NULL DEFAULT 0,
    failed      INTEGER      NOT NULL DEFAULT 0,
    status      VARCHAR(16)  NOT NULL DEFAULT 'running',
    started_at  timestamptz,
    updated_at  timestamptz
);

CREATE UNIQUE INDEX idx_batch_job_id ON batch_jobs (job_id);
CREATE INDEX idx_batch_dataset ON batch_jobs (dataset_id);
CREATE INDEX idx_batch_status  ON batch_jobs (status);

CREATE TABLE auto_prompt_templates (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(100) NOT NULL DEFAULT '',
    case_type            VARCHAR(50)  NOT NULL DEFAULT 'criminal',
    task_type            VARCHAR(50)  NOT NULL DEFAULT 'text_auto_qa',
    system_prompt        TEXT         NOT NULL DEFAULT '',
    user_prompt_template TEXT         NOT NULL DEFAULT '',
    output_schema        TEXT         NOT NULL DEFAULT '',
    guide                TEXT         NOT NULL DEFAULT '',
    enabled              BOOLEAN      NOT NULL DEFAULT TRUE,
    version              INTEGER      NOT NULL DEFAULT 1,
    created_by           BIGINT       NOT NULL DEFAULT 0,
    created_at           timestamptz  NOT NULL DEFAULT now(),
    updated_at           timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX idx_auto_prompt_case_type ON auto_prompt_templates (case_type);
CREATE INDEX idx_auto_prompt_task_type ON auto_prompt_templates (task_type);
CREATE INDEX idx_auto_prompt_enabled   ON auto_prompt_templates (enabled);

-- documents：文本文档表（DocumentDB 的唯一实现，方案-07 起主部署与 runner
-- 共用）。此前只活在 AutoMigrate 里，从未进过版本化迁移——现在进了。
-- data 是 jsonb（M5/M10），检索走 trigram GIN（与 LOWER(...) LIKE 查询配套）。
CREATE TABLE documents (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id               BIGINT       NOT NULL REFERENCES datasets(id) ON DELETE CASCADE,
    doc_key                  VARCHAR(255) NOT NULL,
    version                  INTEGER      NOT NULL DEFAULT 1,
    is_active                BOOLEAN      NOT NULL DEFAULT TRUE,
    user_id                  BIGINT       NOT NULL DEFAULT 0,
    data                     JSONB,
    annotation_stage         VARCHAR(50)  NOT NULL DEFAULT '',
    refinement_cursor        INTEGER      NOT NULL DEFAULT 0,
    created_by               BIGINT       NOT NULL DEFAULT 0,
    created_at               timestamptz  NOT NULL DEFAULT now(),
    updated_at               timestamptz  NOT NULL DEFAULT now(),
    etag                     VARCHAR(64)  NOT NULL DEFAULT '',
    llm_refinement_enabled   BOOLEAN      NOT NULL DEFAULT FALSE,
    llm_refinement_score     INTEGER,
    llm_refinement_reasoning TEXT,
    llm_refinement_version   VARCHAR(64),
    annotator_user_id        VARCHAR(64),
    annotator_name           VARCHAR(100),
    annotator_action_time    timestamptz
);

CREATE UNIQUE INDEX idx_doc_version    ON documents (dataset_id, doc_key, version);
CREATE INDEX idx_doc_active            ON documents (doc_key, is_active);
CREATE INDEX idx_dataset_active        ON documents (dataset_id, is_active);
CREATE INDEX idx_dataset_updated       ON documents (dataset_id, is_active, updated_at);
CREATE INDEX idx_dataset_stage         ON documents (dataset_id, is_active, annotation_stage);
CREATE INDEX idx_dataset_user          ON documents (dataset_id, user_id);
-- M5：文档搜索（LOWER(doc_key) LIKE / LOWER(data::text) LIKE）的加速索引。
CREATE INDEX idx_documents_dockey_trgm ON documents USING gin (lower(doc_key) gin_trgm_ops);
CREATE INDEX idx_documents_data_trgm   ON documents USING gin (lower(data::text) gin_trgm_ops);

-- +goose Down
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS auto_prompt_templates;
DROP TABLE IF EXISTS batch_jobs;
DROP TABLE IF EXISTS upload_sessions;
DROP TABLE IF EXISTS asset_derivatives;
DROP TABLE IF EXISTS annotation_tasks;
DROP TABLE IF EXISTS assets;
DROP TABLE IF EXISTS annotation_logs;
DROP TABLE IF EXISTS extraction_results;
DROP TABLE IF EXISTS llm_providers;
DROP TABLE IF EXISTS system_prompts;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS dataset_industry_tags;
DROP TABLE IF EXISTS dataset_tags;
DROP TABLE IF EXISTS datasets;
DROP TABLE IF EXISTS dataset_functions;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS dataset_categories;
DROP TABLE IF EXISTS users;
